name: "CI"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  qa:
    name: "QA"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3.5.2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.25.1"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "phive"

      - name: "Install dependencies with phive"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "ant install-tools"

      - name: "Run php-cs-fixer"
        run: "ant php-cs-fixer"

      - name: "Run psalm"
        run: "ant psalm"

  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false

      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3.5.2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.25.1"
        env:
          COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          coverage: "pcov"
          extensions: "${{ env.extensions }}"
          ini-values: "display_errors=On, error_reporting=-1, memory_limit=2G"
          php-version: "${{ matrix.php-version }}"
          tools: "phive"

      - name: "Install dependencies with phive"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "ant install-tools"

      - name: "Run PHPUnit with code coverage"
        run: "ant test-with-code-coverage"

      - name: "Send code coverage report to codecov.io"
        uses: "codecov/codecov-action@v3.1.4"
        with:
          files: "build/logs/clover.xml"
